class LMI_StorageJob : LMI_ConcreteJob
{
};

class LMI_StorageMethodResult : LMI_MethodResult
{
};

class LMI_OwningStorageJobElement : LMI_OwningJobElement
{
};


class LMI_AffectedStorageJobElement : LMI_AffectedJobElement
{
};

class LMI_AssociatedStorageJobMethodResult : LMI_AssociatedJobMethodResult
{
};

class LMI_StorageInstModification : CIM_InstModification
{
};

class LMI_StorageInstCreation : CIM_InstCreation
{
};

/*
 Special comment for openlmi-doc-mof2rst to generate documentation of following
 classes:

class CIM_InstMethodCall

*/
